Repository dolittle/platform-api, pull requests merged in 2021-11, with the labels that each got.

#48 Building from terraform is now aware of the platform-environment
  cmd/microservice/build-terraform-info.go
  pkg/platform/storage/git/terraform.go
Labels: patch

#49 Server formatting
  cmd/microservice/server.go
  pkg/middleware/middleware.go
Labels: patch

#51 applications in /applications endpoint return empty []
  pkg/platform/application/service.go
Labels: minor

#50 Endpoints for some credentials
  cmd/microservice/server.go
  pkg/platform/cicd/service.go
  pkg/platform/k8s_repo.go
  pkg/platform/microservice/doc.go
  pkg/platform/microservice/service.go
Labels: minor

#52 Not json + first need to lookup service account
  cmd/microservice/server.go
  pkg/platform/application/service.go
  pkg/platform/cicd/service.go
  pkg/platform/k8s_repo.go
  pkg/platform/microservice/service.go
Labels: patch

#54 Supporting 7.1.0 runtime in the platform
  pkg/dolittle/k8s/configmaps.go
Labels: patch

#55 Increasing the size of our test coverage
  .gitignore
  Makefile
  pkg/platform/microservice/businessmomentsadaptor/suite_test.go
  pkg/platform/microservice/parser/suite_test.go
  pkg/platform/microservice/purchaseorderapi/suite_test.go
  pkg/platform/microservice/rawdatalog/suite_test.go
  pkg/platform/microservice/suite_test.go
  pkg/platform/suite_test.go
  pkg/platform/tenant/suite_test.go
  pkg/rawdatalog/suite_test.go
  pkg/utils/suite_test.go
  scripts/total_coverage.sh
Labels: patch

#57 Expose external url
  cmd/microservice/server.go
  pkg/platform/application/doc.go
  pkg/platform/application/service.go
  pkg/platform/k8s_repo.go
Labels: patch

#58 Add create-service-account command
  cmd/microservice/create-service-account.go
  pkg/platform/k8s_repo.go
Labels: minor

#60 Add creation of a new devops rolebinding for the devops svc acc
  cmd/microservice/create-service-account.go
  pkg/platform/k8s_repo.go
Labels: major

#61 Add ability to create a base microservice without a Runtime container
  pkg/dolittle/k8s/deployment.go
  pkg/platform/microservice/simple_repo.go
Labels: minor

#63 Add runtime-metrics containerport on 9700 for Runtime container
  go.mod
  go.sum
  pkg/dolittle/k8s/configmaps.go
  pkg/dolittle/k8s/configmaps_test.go
  pkg/dolittle/k8s/deployment.go
  pkg/dolittle/k8s/deployment_test.go
  pkg/testutils/k8s.go
Labels: patch

#62 Sharing the git InitGit
  cmd/microservice/build-application-info.go
  cmd/microservice/build-studio-info.go
  cmd/microservice/build-terraform-info.go
  cmd/microservice/git-test.go
  cmd/microservice/root.go
  cmd/microservice/server.go
  cmd/microservice/update-repo.go
  docs/local-development.md
  pkg/git/share.go
Labels: patch
