Repository dolittle/platform-api, pull requests merged in 2022-02, with the labels that each got.

#82 Adding environment to GetMicrosericeName
  pkg/platform/k8s_repo.go
  pkg/platform/k8s_repo_test.go
  pkg/platform/microservice/environmentVariables/repo.go
  pkg/platform/microservice/environmentVariables/service.go
Labels: minor

#83 Reduce the information sent via personalised-info api for documentation
  cmd/microservice/server.go
  pkg/platform/application/doc.go
  pkg/platform/application/service.go
  pkg/platform/doc.go
  pkg/platform/storage/studio_info.go
Labels: minor

#86 Add admin
  cmd/tools/studio/root.go
  cmd/tools/studio/useradmin.go
  pkg/k8s/dolittle.go
Labels: minor

#87 Make it possible to delete api via api
  cmd/microservice/server.go
  cmd/tools/automate/create-application.go
  pkg/k8s/dolittle.go
  pkg/platform/application/k8s/do_test.go
  pkg/platform/application/service_test.go
  pkg/platform/microservice/service.go
  pkg/platform/microservice/simple/k8s/repo.go
Labels: patch

#89 Renaming tenantID to customerID
  cmd/tools/studio/build-application-info.go
  docs/development-application.md
  docs/development-purchase-order-api.md
  docs/microservice.md
  pkg/middleware/middleware.go
  pkg/platform/application/doc.go
  pkg/platform/application/k8s.go
  pkg/platform/application/k8s/do_test.go
  pkg/platform/application/service.go
  pkg/platform/backup/service.go
  pkg/platform/businessmoment/service.go
  pkg/platform/doc.go
  pkg/platform/insights/service.go
  pkg/platform/k8s/k8s_repo.go
  pkg/platform/k8s/k8s_repo_test.go
  pkg/platform/k8s/metadata.go
  pkg/platform/manual/manual.go
  pkg/platform/microservice/handle_businessmomentsadaptor.go
  pkg/platform/microservice/handle_rawdatalogingestor.go
  pkg/platform/microservice/handle_simple.go
  pkg/platform/microservice/k8s/doc.go
  pkg/platform/microservice/parser/parser_json.go
  pkg/platform/microservice/purchaseorderapi/handler.go
  pkg/platform/microservice/purchaseorderapi/k8sResourceSpecFactory.go
  pkg/platform/microservice/purchaseorderapi/repo_test.go
  pkg/platform/microservice/purchaseorderapi/service.go
  pkg/platform/microservice/rawdatalog/repo_test.go
  pkg/platform/microservice/service.go
  pkg/platform/storage/doc.go
  pkg/platform/storage/git/application.go
  pkg/platform/storage/git/businessmoment.go
  pkg/platform/storage/git/customer.go
  pkg/platform/storage/git/microservice.go
  pkg/platform/storage/git/studio.go
  pkg/platform/storage/git/terraform.go
  pkg/platform/storage/mocks/Repo.go
  pkg/platform/storage/mocks/RepoApplication.go
  pkg/platform/storage/mocks/RepoMicroservice.go
  pkg/platform/storage/utils_test.go
Labels: patch

#91 Populate status + welcomeMicroservice from storage if exists
  cmd/tools/studio/build-application-info.go
Labels: minor

#92 Mock mock mock
  .codeclimate.yml
  Makefile
  README.md
  mocks/pkg/k8s/Repo.go
  mocks/pkg/k8s/RepoDeployment.go
  mocks/pkg/k8s/RepoIngress.go
  mocks/pkg/k8s/RepoNamspace.go
  mocks/pkg/k8s/RepoRoleBinding.go
  mocks/pkg/platform/Microservice.go
  mocks/pkg/platform/microservice/businessmomentsadaptor/Repo.go
  mocks/pkg/platform/microservice/environmentVariables/EnvironmentVariablesRepo.go
  mocks/pkg/platform/microservice/parser/Parser.go
  mocks/pkg/platform/microservice/purchaseorderapi/K8sResource.go
  mocks/pkg/platform/microservice/purchaseorderapi/K8sResourceSpecFactory.go
  mocks/pkg/platform/microservice/purchaseorderapi/Repo.go
  mocks/pkg/platform/microservice/simple/Repo.go
  mocks/pkg/platform/storage/Repo.go
  mocks/pkg/platform/storage/RepoApplication.go
  mocks/pkg/platform/storage/RepoCustomer.go
  mocks/pkg/platform/storage/RepoCustomerTenants.go
  mocks/pkg/platform/storage/RepoMicroservice.go
  mocks/pkg/platform/storage/git/GitSync.go
  mocks/pkg/rawdatalog/Repo.go
  pkg/platform/application/k8s/do_test.go
  pkg/platform/application/service_test.go
Labels: minor

#90 Refactor CLI commands
  README.md
  cmd/api/git-test.go
  cmd/api/root.go
  cmd/api/server.go
  cmd/api/update-repo.go
  cmd/rawdatalog/server.go
  cmd/root.go
  cmd/template/delete/application.go
  cmd/template/delete/customer.go
  cmd/template/delete/root.go
  cmd/template/root.go
  cmd/tools/automate/pull-microservice-deployment.go
  cmd/tools/automate/root.go
  cmd/tools/explore/microservices.go
  cmd/tools/explore/root.go
  cmd/tools/job/root.go
  cmd/tools/job/status.go
  cmd/tools/job/template/application.go
  cmd/tools/job/template/customer.go
  cmd/tools/job/template/root.go
  cmd/tools/jobs/root.go
  cmd/tools/root.go
  cmd/tools/studio/create/root.go
  cmd/tools/studio/create/service-account.go
  cmd/tools/studio/get/customers.go
  cmd/tools/studio/get/root.go
  cmd/tools/studio/root.go
  cmd/tools/studio/upsert/application.go
  cmd/tools/studio/upsert/root.go
  cmd/tools/studio/upsert/studio.go
  cmd/tools/studio/upsert/terraform.go
  cmd/tools/terraform/root.go
  cmd/tools/terraform/template/application.go
  cmd/tools/terraform/template/customer.go
  cmd/tools/terraform/template/root.go
  pkg/platform/job/k8s/application.go
  pkg/platform/job/k8s/common.go
  pkg/platform/job/k8s/customer.go
Labels: major
