Repository dolittle/platform-api, pull requests merged in 2022-06, with the labels that each got.

#131 Add reusable container and configmap workflows
  .github/workflows/release-and-deploy.yml
  .github/workflows/update-configmap-field.yml
  .github/workflows/update-container-image.yml
Labels: patch

#132 Fix typo in deploy jobs
  .github/workflows/release-and-deploy.yml
Labels: patch

#133 Fix typo
  .github/workflows/update-container-image.yml
Labels: patch

#134 Fix the needs of the deploy workflow
  .github/workflows/release-and-deploy.yml
Labels: patch

#135 Fix environment url check for configmaps
  .github/workflows/update-configmap-field.yml
Labels: no-release

#136 Add new deploy workflow to consolidate the steps
  .github/workflows/deploy.yml
  .github/workflows/release-and-deploy.yml
Labels: patch

#137 Add Studio urls to deployement. Move reusable workflows to Studio repo
  .github/workflows/deploy.yml
  .github/workflows/release-and-deploy.yml
  .github/workflows/update-configmap-field.yml
  .github/workflows/update-container-image.yml
Labels: patch

#138 Fix deploy typo
  .github/workflows/deploy.yml
Labels: patch

#141 Command to copy env variables for a microservice from en env to a new env
  cmd/tools/microservice/copy/environment.go
  cmd/tools/microservice/copy/root.go
  cmd/tools/microservice/root.go
  cmd/tools/root.go
Labels: minor

#140 Add tools eventhorizon add command
  cmd/tools/eventhorizon/add.go
  cmd/tools/eventhorizon/root.go
  cmd/tools/root.go
  mocks/pkg/platform/microservice/simple/Repo.go
  pkg/dolittle/k8s/configmaps.go
  pkg/platform/microservice/doc.go
  pkg/platform/microservice/service.go
  pkg/platform/microservice/simple/doc.go
  pkg/platform/microservice/simple/k8s/k8s_suite_test.go
  pkg/platform/microservice/simple/k8s/repo.go
  pkg/platform/microservice/simple/k8s/repo_test.go
  pkg/platform/microservice/simple/simple.go
Labels: minor
