Repository dolittle/platform-api, pull requests merged in 2022-01, with the labels that each got.

#71 Disabling create + update + delete of microservice
  pkg/platform/microservice/service.go
Labels: patch

#74 Add import-dolittle-configmaps
  cmd/tools/automate/import-dolittle-configmaps.go
  cmd/tools/automate/root.go
Labels: minor

#75 Make release label action to only run on PRs that target main
  .github/workflows/check-labels.yml
  Makefile
Labels: no-release

#77 Fix getServiceAccountCredentials to return the whole k8s Secret resource
  pkg/platform/cicd/service.go
Labels: patch

#73 Add commands to pull configmaps & deployments and to update them with the `platform.json`
  cmd/tools/automate/add-platform-config.go
  cmd/tools/automate/get-microservices-metadata.go
  cmd/tools/automate/import-dolittle-configmaps.go
  cmd/tools/automate/pull-dolittle-config.go
  cmd/tools/automate/pull-microservice-deployment.go
  cmd/tools/automate/root.go
  cmd/tools/root.go
  cmd/tools/studio/build-studio-info.go
  cmd/tools/studio/share.go
  pkg/dolittle/k8s/configmaps.go
  pkg/dolittle/k8s/deployment.go
  pkg/dolittle/k8s/deployment_test.go
  pkg/platform/automate/command_input.go
  pkg/platform/automate/doc.go
  pkg/platform/automate/share.go
  pkg/platform/doc.go
  pkg/platform/k8s_repo.go
  pkg/platform/microservice/businessmomentsadaptor_repo.go
  pkg/platform/microservice/k8s/doc.go
  pkg/platform/microservice/purchaseorderapi/k8sResource.go
  pkg/platform/microservice/purchaseorderapi/repo.go
  pkg/platform/microservice/simple_repo.go
Labels: minor

#79 Make `GetDeployment` environment aware
  cmd/tools/automate/add-platform-config.go
  pkg/platform/automate/share.go
  pkg/platform/microservice/businessmomentsadaptor_repo.go
  pkg/platform/microservice/purchaseorderapi/doc.go
  pkg/platform/microservice/purchaseorderapi/handler.go
  pkg/platform/microservice/purchaseorderapi/k8sResource.go
  pkg/platform/microservice/purchaseorderapi/repo.go
  pkg/platform/microservice/rawdatalog/repo.go
  pkg/platform/microservice/service.go
  pkg/platform/microservice/simple_repo.go
Labels: patch

#80 Make add-platform-config command more robust
  cmd/tools/automate/add-platform-config.go
  pkg/platform/automate/share.go
Labels: patch

#81 Share k8s setup
  cmd/microservice/server.go
  cmd/tools/automate/add-platform-config.go
  cmd/tools/automate/get-microservices-metadata.go
  cmd/tools/automate/import-dolittle-configmaps.go
  cmd/tools/automate/pull-dolittle-config.go
  cmd/tools/automate/pull-microservice-deployment.go
  cmd/tools/studio/build-application-info.go
  cmd/tools/studio/build-studio-info.go
  cmd/tools/studio/create-service-account.go
  pkg/platform/k8s/setup.go
  pkg/platform/k8s_repo.go
Labels: patch
