Repository dolittle/platform-api, pull requests merged in 2022-04, with the labels that each got.

#105 Feature head port
  pkg/platform/doc.go
  pkg/platform/microservice/handle_simple.go
  pkg/platform/microservice/simple/k8s/resources.go
  pkg/platform/microservice/simple/k8s/resources_test.go
  pkg/platform/microservice/simple/k8s/suite_test.go
Labels: minor

#108 Fix release workflow to only run when a pull request is merged
  .github/workflows/release.yml
Labels: no-release

#107 Add support for V8 Runtime with backwards compatibility set to V7 by default
  pkg/dolittle/k8s/configmaps.go
  pkg/dolittle/k8s/configmaps_test.go
  pkg/platform/microservice/simple/k8s/resources.go
  pkg/platform/microservice/simple/k8s/resources_test.go
Labels: minor

#104 Add codecoverage reporting on PR's
  .github/workflows/pull-request.yml
  .github/workflows/release.yml
Labels: no-release

#109 Create application, environments can have custom ids
  cmd/tools/terraform/template/application.go
  pkg/platform/application/doc.go
  pkg/platform/application/k8s.go
  pkg/platform/application/service.go
Labels: minor

#110 Fix release workflow
  .github/workflows/release.yml
Labels: minor

#106 Able to list emails, add email, remove email
  cmd/api/server.go
  cmd/tools/application/access.go
  cmd/tools/application/root.go
  cmd/tools/root.go
  cmd/tools/users/remove.go
  go.mod
  go.sum
  mocks/pkg/platform/application/UserAccess.go
  mocks/pkg/platform/user/KratosClientV5.go
  mocks/pkg/platform/user/UserActiveDirectory.go
  pkg/platform/application/doc.go
  pkg/platform/application/service.go
  pkg/platform/application/service_test.go
  pkg/platform/application/service_user.go
  pkg/platform/application/service_user_test.go
  pkg/platform/application/useraccess.go
  pkg/platform/application/useraccessinmemory.go
  pkg/platform/customer/service.go
  pkg/platform/job/k8s/application.go
  pkg/platform/user/activedirectory.go
  pkg/platform/user/application.go
  pkg/platform/user/kratos.go
  pkg/platform/user/model.go
Labels: minor

#112 Enable head container commands and args to be defined on microservice creation
  docs/microservice.md
  pkg/platform/doc.go
  pkg/platform/microservice/simple/k8s/resources.go
  pkg/platform/microservice/simple/k8s/resources_test.go
Labels: minor

#113 Studio include kafka
  cmd/api/server.go
  pkg/platform/application/doc.go
  pkg/platform/application/service.go
  pkg/platform/doc.go
  pkg/platform/listeners/doc.go
  pkg/platform/listeners/m3connector/kafkafiles.go
  pkg/platform/microservice/handle_simple.go
  pkg/platform/microservice/service.go
  pkg/platform/microservice/simple/k8s/resources.go
  pkg/platform/microservice/simple/k8s/resources_test.go
  pkg/platform/storage/doc.go
  pkg/platform/storage/environment.go
Labels: minor

#114 unused flag + wrong text
  cmd/tools/job/template/customer.go
  cmd/tools/terraform/template/customer.go
Labels: patch
